# LSTM Stock Predictor Using Fear and Greed Index

In this notebook, you will build and train a custom LSTM RNN that uses a 10 day window of Bitcoin fear and greed index values to predict the 11th day closing price. 

You will need to:

1. Prepare the data for training and testing
2. Build and train a custom LSTM RNN
3. Evaluate the performance of the model

## Data Preparation

In this section, you will need to prepare the training and testing data for the model. The model will use a rolling 10 day window to predict the 11th day closing price.

You will need to:
1. Use the `window_data` function to generate the X and y values for the model.
2. Split the data into 70% training and 30% testing
3. Apply the MinMaxScaler to the X and y values
4. Reshape the X_train and X_test data for the model. Note: The required input format for the LSTM is:

```python
reshape((X_train.shape[0], X_train.shape[1], 1))
```

In [393]:
import numpy as np
import pandas as pd
import hvplot.pandas

In [394]:
# Set the random seed for reproducibility
# Note: This is for the homework solution, but it is good practice to comment this out and run multiple experiments to evaluate your model
from numpy.random import seed
seed(1)
from tensorflow import random
random.set_seed(2)

In [395]:
# Load the fear and greed sentiment data for Bitcoin
df = pd.read_csv('btc_sentiment.csv', index_col="date", infer_datetime_format=True, parse_dates=True)
df = df.drop(columns="fng_classification")
df.head()

fng_value
date                  
2019-07-29          19
2019-07-28          16
2019-07-27          47
2019-07-26          24
2019-07-25          42

In [396]:
# Load the historical closing prices for Bitcoin
df2 = pd.read_csv('btc_historic.csv', index_col="Date", infer_datetime_format=True, parse_dates=True)['Close']
df2 = df2.sort_index()
df2.tail()

Date
2019-07-25    9882.429688
2019-07-26    9847.450195
2019-07-27    9478.320313
2019-07-28    9531.769531
2019-07-29    9529.889648
Name: Close, dtype: float64

In [397]:
# Join the data into a single DataFrame
df = df.join(df2, how="inner")
df.tail()

fng_value        Close
2019-07-25          42  9882.429688
2019-07-26          24  9847.450195
2019-07-27          47  9478.320313
2019-07-28          16  9531.769531
2019-07-29          19  9529.889648

In [398]:
df.head()

fng_value        Close
2018-02-01          30  9114.719727
2018-02-02          15  8870.820313
2018-02-03          40  9251.269531
2018-02-04          24  8218.049805
2018-02-05          11  6937.080078

In [399]:
# This function accepts the column number for the features (X) and the target (y)
# It chunks the data up with a rolling window of Xt-n to predict Xt
# It returns a numpy array of X any y
def window_data(df, window, feature_col_number, target_col_number):
    X = []
    y = []
    for i in range(len(df) - window - 1):
        features = df.iloc[i:(i + window), feature_col_number]
        target = df.iloc[(i + window), target_col_number]
        X.append(features)
        y.append(target)
    return np.array(X), np.array(y).reshape(-1, 1)

In [400]:
# Predict Closing Prices using a 10 day window of previous fng values
# Then, experiment with window sizes anywhere from 1 to 10 and see how the model performance changes
window_size = 10

# Column index 0 is the 'fng_value' column
# Column index 1 is the `Close` column
feature_column = 0
target_column = 1
X, y = window_data(df, window_size, feature_column, target_column)

In [401]:
# Use 70% of the data for training and the remaineder for testing
# YOUR CODE HERE!
split = int(0.7 * len(X))
X_train = X[: split - 1]
X_test = X[split:]
y_train = y[: split - 1]
y_test = y[split:]

In [402]:
from sklearn.preprocessing import MinMaxScaler
# Use the MinMaxScaler to scale data between 0 and 1.
# YOUR CODE HERE!
X_train_scaler = MinMaxScaler()
X_test_scaler = MinMaxScaler()
y_train_scaler = MinMaxScaler()
y_test_scaler = MinMaxScaler()

X_train_scaler.fit(X_train)
X_test_scaler.fit(X_test)
y_train_scaler.fit(y_train)
y_test_scaler.fit(y_test)

X_train = X_train_scaler.transform(X_train)
X_test = X_test_scaler.transform(X_test)
y_train = y_train_scaler.transform(y_train)
y_test = y_test_scaler.transform(y_test)

X_train[:5]

array([[0.33333333, 0.10606061, 0.48484848, 0.24242424, 0.04545455,
        0.        , 0.41538462, 0.32307692, 0.53846154, 0.69230769],
       [0.10606061, 0.48484848, 0.24242424, 0.04545455, 0.        ,
        0.42424242, 0.32307692, 0.53846154, 0.69230769, 0.33846154],
       [0.48484848, 0.24242424, 0.04545455, 0.        , 0.42424242,
        0.33333333, 0.53846154, 0.69230769, 0.33846154, 0.50769231],
       [0.24242424, 0.04545455, 0.        , 0.42424242, 0.33333333,
        0.54545455, 0.69230769, 0.33846154, 0.50769231, 0.4       ],
       [0.04545455, 0.        , 0.42424242, 0.33333333, 0.54545455,
        0.6969697 , 0.33846154, 0.50769231, 0.4       , 0.70769231]])

In [403]:
# Reshape the features for the model
# YOUR CODE HERE!
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))
print (f"X_train sample values:\n{X_train[:5]} \n")
print (f"X_test sample values:\n{X_test[:5]}")

X_train sample values:
[[[0.33333333]
  [0.10606061]
  [0.48484848]
  [0.24242424]
  [0.04545455]
  [0.        ]
  [0.41538462]
  [0.32307692]
  [0.53846154]
  [0.69230769]]

 [[0.10606061]
  [0.48484848]
  [0.24242424]
  [0.04545455]
  [0.        ]
  [0.42424242]
  [0.32307692]
  [0.53846154]
  [0.69230769]
  [0.33846154]]

 [[0.48484848]
  [0.24242424]
  [0.04545455]
  [0.        ]
  [0.42424242]
  [0.33333333]
  [0.53846154]
  [0.69230769]
  [0.33846154]
  [0.50769231]]

 [[0.24242424]
  [0.04545455]
  [0.        ]
  [0.42424242]
  [0.33333333]
  [0.54545455]
  [0.69230769]
  [0.33846154]
  [0.50769231]
  [0.4       ]]

 [[0.04545455]
  [0.        ]
  [0.42424242]
  [0.33333333]
  [0.54545455]
  [0.6969697 ]
  [0.33846154]
  [0.50769231]
  [0.4       ]
  [0.70769231]]] 

X_test sample values:
[[[0.30379747]
  [0.37974684]
  [0.27848101]
  [0.40506329]
  [0.40506329]
  [0.34177215]
  [0.34177215]
  [0.3164557 ]
  [0.27848101]
  [0.59493671]]

 [[0.37974684]
  [0.27848101]
  [0.405063

In [404]:
X_test.shape

(160, 10, 1)

---

## Build and Train the LSTM RNN

In this section, you will design a custom LSTM RNN and fit (train) it using the training data.

You will need to:
1. Define the model architecture
2. Compile the model
3. Fit the model to the training data

### Hints:
You will want to use the same model architecture and random seed for both notebooks. This is necessary to accurately compare the performance of the FNG model vs the closing price model. 

In [405]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
import tensorflow as tf

In [406]:
# Build the LSTM model. 
# The return sequences need to be set to True if you are adding additional LSTM layers, but 
# You don't have to do this for the final layer. 
# Note: The dropouts help prevent overfitting
# Note: The input shape is the number of time steps and the number of indicators
# Note: Batching inputs has a different input shape of Samples/TimeSteps/Features

# YOUR CODE HERE!

# Define the LSTM RNN model
model = Sequential()

# Layer 1
model.add(LSTM(units=30, return_sequences = True, input_shape = (X_train.shape[1], 1)))
model.add(Dropout(0.2))

# Layer 2
model.add(LSTM(units=30, return_sequences = True))
model.add(Dropout(0.2))

# Layer 3
model.add(LSTM(units=30))
model.add(Dropout(0.2))

# Output layer
model.add(Dense(units=1))

In [407]:
# Compile the model
# YOUR CODE HERE!
model.compile(
    loss="mean_squared_error",
    optimizer="adam"
)

In [408]:
# Summarize the model
# YOUR CODE HERE!
model.summary()

Model: "sequential_26"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_75 (LSTM)               (None, 10, 30)            3840      
_________________________________________________________________
dropout_74 (Dropout)         (None, 10, 30)            0         
_________________________________________________________________
lstm_76 (LSTM)               (None, 10, 30)            7320      
_________________________________________________________________
dropout_75 (Dropout)         (None, 10, 30)            0         
_________________________________________________________________
lstm_77 (LSTM)               (None, 30)                7320      
_________________________________________________________________
dropout_76 (Dropout)         (None, 30)                0         
_________________________________________________________________
dense_24 (Dense)             (None, 1)               

In [409]:
# Train the model
# Use at least 10 epochs
# Do not shuffle the data
# Experiement with the batch size, but a smaller batch size is recommended
# YOUR CODE HERE!
batch_size = 1
epochs = 10
model.fit(
    X_train,
    y_train,
    epochs=epochs,
    batch_size=batch_size,
    verbose=1,
)

Epoch 1/10
371/371 [==============================] - 3s 8ms/step - loss: 0.0569
Epoch 2/10
371/371 [==============================] - 3s 7ms/step - loss: 0.0482
Epoch 3/10
371/371 [==============================] - 3s 7ms/step - loss: 0.0491
Epoch 4/10
371/371 [==============================] - 3s 7ms/step - loss: 0.0455
Epoch 5/10
371/371 [==============================] - 3s 7ms/step - loss: 0.0469
Epoch 6/10
371/371 [==============================] - 3s 7ms/step - loss: 0.0471
Epoch 7/10
371/371 [==============================] - 3s 7ms/step - loss: 0.0475
Epoch 8/10
371/371 [==============================] - 3s 7ms/step - loss: 0.0438
Epoch 9/10
371/371 [==============================] - 3s 7ms/step - loss: 0.0475
Epoch 10/10
371/371 [==============================] - 3s 7ms/step - loss: 0.0460


---

## Model Performance

In this section, you will evaluate the model using the test data. 

You will need to:
1. Evaluate the model using the `X_test` and `y_test` data.
2. Use the X_test data to make predictions
3. Create a DataFrame of Real (y_test) vs predicted values. 
4. Plot the Real vs predicted values as a line chart

### Hints
Remember to apply the `inverse_transform` function to the predicted and y_test values to recover the actual closing prices.

In [410]:
# Evaluate the model
# YOUR CODE HERE!
model.evaluate(X_test, y_test)

5/5 [==============================] - 0s 4ms/step - loss: 0.1021


0.10212397575378418

In [411]:
# Make some predictions
# YOUR CODE HERE!
predicted = model.predict(X_test)

In [412]:
# Recover the original prices instead of the scaled version
predicted_prices = y_test_scaler.inverse_transform(predicted)
real_prices = y_test_scaler.inverse_transform(y_test.reshape(-1, 1))

In [413]:
# Create a DataFrame of Real and Predicted values
stocks = pd.DataFrame({
    "Real": real_prices.ravel(),
    "Predicted": predicted_prices.ravel()
    }, index = df.index[-len(real_prices): ])
stocks.head()

Real    Predicted
2019-02-20  3924.239990  7560.942871
2019-02-21  3974.050049  7766.484863
2019-02-22  3937.040039  7970.374512
2019-02-23  3983.530029  8177.996094
2019-02-24  4149.089844  8340.108398

In [414]:
# Plot the real vs predicted values as a line chart
# YOUR CODE HERE!
stocks.hvplot(title="Real vs. Predicted Stock Price")

:NdOverlay   [Variable]
   :Curve   [index]   (value)